### ISSUE TITLE
Clicking on any column of the "Logged As" grid results in an error

### ISSUE THREAD

**Issue by mystix** [flancer32/mage2_ext_login_as#16] opened 2019-05-21 10:25 UTC
Clicking on any column of the "Logged As" grid causes the following error popup to be displayed:
![Screenshot 2019-05-21 at 6 22 43 PM](https://user-images.githubusercontent.com/174070/58088535-79ab8a80-7bf5-11e9-95e4-74dbe968b3ba.png)

The corresponding SQL query that is generated when clicking any column:
```
SELECT `log`.`id` AS `Id`, `log`.`customer_ref` AS `CustId`, `log`.`user_ref` AS `AdminId`, `log`.`date` AS `DateLogged`, `cust`.`entity_id`
LEFT JOIN `customer_entity` AS `cust` ON cust.entity_id=log.customer_ref
LEFT JOIN `admin_user` AS `adm` ON adm.user_id=log.user_ref 
ORDER BY `(CONCAT(adm`.`firstname, ' ', adm`.`lastname, ' <', adm`.`email, '>'))` ASC
LIMIT 20
```

It appears the FROM clause goes missing when sorting.

**Comment by flancer64** [comment] 2019-05-22 08:30
Thanks, Marc. This issue should be fixed in mage2_ext_login_as v0.2.1 & flancer32/mage2_ext_base v0.2.0.

**Comment by mystix** [comment] 2019-05-23 06:24
Unfortunately the error persists even after upgrading to mage2_ext_login_as v0.2.1 & flancer32/mage2_ext_base v0.2.0.

The new SQL being generated is:
```
SELECT `log`.`id` AS `Id`, `log`.`customer_ref` AS `CustId`, `log`.`user_ref` AS `AdminId`, `log`.`date` AS `DateLogged`, (CONCAT(cust.firstname, ' ', cust.lastname, ' <', cust.email, '>')) AS `Customer`, (CONCAT(adm.firstname, ' ', adm.lastname, ' <', adm.email, '>')) AS `Admin` 
FROM `fl32_loginas_log` AS `log`
LEFT JOIN `customer_entity` AS `cust` ON cust.entity_id=log.customer_ref
LEFT JOIN `admin_user` AS `adm` ON adm.user_id=log.user_ref 
ORDER BY `(CONCAT(cust`.`firstname, ' ', cust`.`lastname, ' <', cust`.`email, '>'))` ASC
LIMIT 20
```

which gives the following error message when run:
`Syntax error near '.`email, '>'))` ASC LIMIT 20'`

The correct syntax for the `CONCAT` line should be:
`ORDER BY CONCAT(`cust`.`firstname`, ' ', `cust`.`lastname`, ' <', `cust`.`email`, '>') ASC`
but it's somehow getting mangled by the code.

**Comment by flancer64** [comment] 2019-05-23 08:54
The problem is in 
```
ORDER BY `(CONCAT(cust`.`firstname, ' ', cust`.`lastname, ' <', cust`.`email, '>'))` ASC`
```
 of SQL. 

This part is generated by [\Flancer32\Base\App\Ui\DataProvider\Adapter\ApiSearchCriteria::getOrderFromApiCriteria](https://github.com/flancer32/mage2_ext_base/blob/master/App/Ui/DataProvider/Adapter/ApiSearchCriteria.php#L87)

I have installed `mage2_ext_login_as` into M2 app:
```
$ composer require flancer32/mage2_ext_login_as
Using version ^0.2.1 for flancer32/mage2_ext_login_as           
./composer.json has been updated
Loading composer repositories with package information                                                                                                Updating dependencies (including require-dev)         Package operations: 2 installs, 0 updates, 0 removals
  - Installing flancer32/mage2_ext_base (0.1.0): Loading from cache
  - Installing flancer32/mage2_ext_login_as (0.2.1): Downloading (100%)         
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

As I see, `flancer32/mage2_ext_base` ext is installed as `0.1.0`. I suppose, there are some troubles with versioning on Packagist.

**Comment by flancer64** [comment] 2019-05-23 09:10
Yes, this is a Packagist related problem. @mystix, please, run these commands to update base ext to 0.2.0 version:
```
$ composer config repositories.mage2_ext_base vcs https://github.com/flancer32/mage2_ext_base
$ composer require flancer32/mage2_ext_base:0.2.0
```

**Closed as completed by flancer64** 2019-05-23 09:10 UTC

**Comment by flancer64** [comment] 2019-05-23 09:34
U-ups... I have an error:
```
$ composer require flancer32/mage2_ext_base:0.2.0
                                                                
In InitCommand.php line 697:
                                                                               
  Could not find package flancer32/mage2_ext_base in a version matching 0.2.0  
                                                                               

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

Probably, there are some troubles with release on Github.

**Comment by flancer64** [comment] 2019-05-23 10:04
I found the reason. I had "version" node in my "composer.json" for base-module with value "0.1.0"
```
{
  "name": "flancer32/mage2_ext_base",
  ...
  "version": "0.1.0",
  ...
}
```

I've removed it and it's OK now.

**Comment by mystix** [comment] 2019-05-23 10:12
Awesome! Will you be pushing a new package?

**Comment by flancer64** [comment] 2019-05-23 10:18
Yes, I just pushed new releases and validated it:
```
$ composer require flancer32/mage2_ext_login_as
Using version ^0.2.1 for flancer32/mage2_ext_login_as           
./composer.json has been updated
Loading composer repositories with package information                                                                                                Updating dependencies (including require-dev)         Package operations: 2 installs, 0 updates, 0 removals
  - Installing flancer32/mage2_ext_base (0.2.0): Downloading (100%)         
  - Installing flancer32/mage2_ext_login_as (0.2.1): Downloading (100%)         
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```
Try to remove & install module `flancer32/mage2_ext_login_as` with composer.

**Comment by mystix** [comment] 2019-05-23 10:25
Verified 👍 
```
✗ composer require flancer32/mage2_ext_login_as
Using version ^0.2.1 for flancer32/mage2_ext_login_as
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing flancer32/mage2_ext_base (0.2.0): Downloading (100%)         
  - Installing flancer32/mage2_ext_login_as (0.2.1): Downloading (100%)         
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

Thanks for the quick turnaround!
